import { describe, expect, it } from 'vitest';
import { convertPages, type ConvertInput, type ConvertResult } from '../../lib/convert';
import { displayWidth } from '../../lib/convert/shared';
import type { CoverInfo } from '../../lib/messages';
import { FULL_PAGE, IFRAME, JIRA_TABLE, PAGE_ID } from './fixtures/exportView';
import {
  ANCHORS,
  CJK_TABLE,
  CODE_WITH_BACKTICKS,
  COMPLEX_TABLE,
  DC9_EXPAND,
  STRAY_BREAKS,
  EMOTICONS,
  HEADERLESS_TABLE,
  IMAGES_DEDUPE,
  INLINE_PLACEHOLDER,
  NESTED_LISTS,
  PANELS,
  SPECIAL_CHARS,
  WIDE_TABLE,
  body,
  convertInput,
  newDoc,
  ref,
} from './fixtures/convert';

const COVER: CoverInfo = {
  title: 'Checkout v3',
  sourceUrl: 'https://acme.atlassian.net/wiki/spaces/ENG/pages/100',
  spaceKey: 'ENG',
  exportedAt: '2026-10-06T08:30:00.000Z',
  exportedBy: 'Jane Doe',
  pageCount: 3,
  siteTitle: 'Acme Wiki',
};

function convert(input: ConvertInput): ConvertResult {
  return convertPages(newDoc(), input);
}

function textInput(pages: ConvertInput['pages'], o: Parameters<typeof convertInput>[1] = {}): ConvertInput {
  return convertInput(pages, { ...o, options: { format: 'text', ...o.options } });
}

/** Text of a single page with the given HTML (no meta), without the title block. */
function txt(html: string): string {
  const r = convert(textInput([{ ref: ref('200', 'Page', 0), body: body('200', 'Page', html) }], { options: { includePageMeta: false } }));
  const text = r.files[0]!.text;
  expect(text.startsWith('Page\n====\n\n')).toBe(true);
  return text.slice('Page\n====\n\n'.length);
}

const ROOT = ref(PAGE_ID, 'Checkout v3 Tech Spec', 0);
const CHILD = ref('111', 'Architecture', 1, { parentId: PAGE_ID });
const FOLDER = ref('300', 'Runbooks', 1, { type: 'folder', parentId: PAGE_ID });
const IN_FOLDER = ref('301', 'On-call', 2, { parentId: '300' });
const SKIPPED = ref('114', 'Secret page', 1, { parentId: PAGE_ID });

function tree(o: Parameters<typeof convertInput>[1] = {}): ConvertInput {
  const pages = [
    { ref: ROOT, body: body(PAGE_ID, 'Checkout v3 Tech Spec', FULL_PAGE) },
    {
      ref: CHILD,
      body: body('111', 'Architecture', '<h1 id="Architecture-Top">Top</h1><p>Back to <a href="/wiki/spaces/ENG/pages/315494566/Checkout#CheckoutV3TechSpec-Details">details</a>.</p>'),
    },
    { ref: FOLDER },
    { ref: IN_FOLDER, body: body('301', 'On-call', '<p>Pager duty.</p>') },
    { ref: SKIPPED, body: body('114', 'Secret page', '<p>hidden</p>') },
  ];
  return textInput(pages, { excludeIds: ['114'], ...o });
}

describe('convertPages (text) — document', () => {
  it('writes one .txt with underlined titles and page separators', () => {
    const r = convert(tree());
    expect(r.files.map((f) => f.path)).toEqual(['ENG_Checkout v3_2026-10-06.txt']);
    expect(r.assets).toEqual([]);
    const text = r.files[0]!.text;
    expect(text.startsWith('Checkout v3 Tech Spec\n=====================\n\nPath: Engineering › Payments\n')).toBe(true);
    expect(text).toContain(`\n\n${'='.repeat(72)}\n\nArchitecture\n============\n`);
    expect(text).toContain('Last updated: 2026-09-30 by Jane Doe (version 7)\nURL: https://acme.atlassian.net/wiki/spaces/ENG/pages/111');
    expect(text).not.toContain('Secret page');
    expect(text).not.toMatch(/<\/?[a-z][^>]*>/i);
    expect(text).not.toMatch(/[ \t]+$/m);
    expect(text).not.toContain('\r');
    expect(text.endsWith('\n')).toBe(true);
  });

  it('writes a cover block and an indented TOC', () => {
    const text = convert(tree({ cover: COVER, toc: true })).files[0]!.text;
    expect(text.startsWith('Checkout v3\n===========\n\nSite:        Acme Wiki\nSource:      https://acme.atlassian.net/wiki/spaces/ENG/pages/100\n')).toBe(true);
    expect(text).toContain('Space:       ENG\nExported:    2026-10-06 08:30 UTC\nExported by: Jane Doe\nPages:       3\n\nGenerated by Fast PDF Export for Confluence v1.0.0');
    expect(text).toContain('Contents\n--------\n\nCheckout v3 Tech Spec\n  Architecture\n  Runbooks [Folder]\n    On-call\n');
  });

  it('omits meta, cover and TOC when off', () => {
    const text = convert(tree({ options: { includePageMeta: false } })).files[0]!.text;
    expect(text).not.toContain('URL:');
    expect(text).not.toContain('Contents');
    expect(text).toContain('Architecture\n============\n\nTop\n---\n\nBack to details.');
  });

  it('lists folder contents and in-document links as plain text', () => {
    const text = convert(tree()).files[0]!.text;
    expect(text).toContain('Runbooks\n========\n\nType: Folder\nURL: https://acme.atlassian.net/wiki/spaces/ENG/pages/300\n\nThis folder contains:\n- On-call');
    expect(text).toContain('See Architecture, Glossary terms (https://acme.atlassian.net/wiki/spaces/ENG/pages/222/Glossary#Glossary-Terms), Runbook (');
    expect(text).toContain(', legacy link, tiny self link, overview, bad, external (https://example.com/docs), spec.pdf (');
  });

  it('writes separate files with a contents index', () => {
    const r = convert(tree({ separate: true, toc: true }));
    expect(r.files.map((f) => f.path)).toEqual([
      '00-Contents.txt',
      '01-Checkout v3 Tech Spec.txt',
      '02-Architecture.txt',
      '03-Runbooks.txt',
      '04-On-call.txt',
    ]);
    expect(r.files[0]!.text).toContain('Checkout v3 Tech Spec (01-Checkout v3 Tech Spec.txt)\n  Architecture (02-Architecture.txt)');
    expect(r.files[2]!.text).toContain('Back to details (01-Checkout v3 Tech Spec.txt).');
    expect(r.files[3]!.text).toContain('- On-call (04-On-call.txt)');
    expect(r.files.every((f) => !f.text.includes('='.repeat(72)))).toBe(true);
  });
});

describe('convertPages (text) — content', () => {
  it('renders headings, panels, code, expand, status and tasks', () => {
    const text = txt(FULL_PAGE);
    expect(text.startsWith('Overview\n--------\n\nIntro.\n\nDetails\n\nFine print\n\n')).toBe(true);
    expect(text).toContain('[Info] Payments go through the new gateway.');
    expect(text).toContain('[Warning] Careful\n  Do not deploy on Fridays.');
    expect(text).toContain('    public class Checkout {\n      void pay()');
    expect(text).toContain('Show the rollout plan\n  Week 1: internal users.');
    expect(text).toContain('State: [IN PROGRESS]');
    expect(text).toContain('[x] Write spec\n[ ] Review spec');
    expect(text).toContain('🙂 😀');
  });

  it("underlines the page's top heading level, whatever it is", () => {
    // Pages written with h2/h3 only (common on Cloud and DC): demoted to h3/h4 below the title.
    expect(txt('<h2>Copilot</h2><p>Intro.</p><h3>Copilot Chat</h3><p>Free.</p>')).toBe(
      'Copilot\n-------\n\nIntro.\n\nCopilot Chat\n\nFree.\n',
    );
    expect(txt('<h1>Top</h1><h2>Sub</h2><h3>Deep</h3>')).toBe('Top\n---\n\nSub\n\nDeep\n');
  });

  it('keeps expand titles and drops stray line breaks', () => {
    expect(txt(DC9_EXPAND)).toBe('Introduction\n  The project publishes releases.\n');
    expect(txt(STRAY_BREAKS)).toBe('Motivation text.\n\n- Before (multiple --property options):\n\n      run \\\n        --x\n\nkeep\nthis break\n');
  });

  it('indents code blocks and keeps their title', () => {
    expect(txt(CODE_WITH_BACKTICKS)).toBe('README.md:\n\n    Run it:\n    ```\n    npm test\n    ```\n    then ````done````\n');
  });

  it('renders panel variants', () => {
    expect(txt(PANELS)).toBe(
      '[Note] Mind the gap.\n\n  - one\n\n[Tip] Use the cache.\n\n[Release notes]\n  Version 2 is out.\n\nPlain callout.\n',
    );
  });

  it('aligns table columns with a header rule', () => {
    expect(txt(FULL_PAGE)).toContain('Field  | Description\n-------+------------\nid     | Primary key\namount | Minor units');
    expect(txt(JIRA_TABLE)).toBe(
      'Key                                             | Summary        | Status\n' +
        '------------------------------------------------+----------------+-------\n' +
        'PAY-1 (https://acme.atlassian.net/browse/PAY-1) | Add card vault | [DONE]\n',
    );
    expect(txt(HEADERLESS_TABLE)).toBe('a|b           | line 1 line 2\npara 1 para 2 | bold\n');
  });

  it('pads by display width (CJK, emoji)', () => {
    expect(txt(CJK_TABLE)).toBe('名前 | Note\n-----+------\n東京 | x\nab   | 😀 ok\n');
    expect(displayWidth('東京')).toBe(4);
    expect(displayWidth('😀')).toBe(2);
    expect(displayWidth('é')).toBe(1);
  });

  it('falls back to separated rows for wide tables', () => {
    const text = txt(WIDE_TABLE);
    expect(text.split('\n')[0]).toBe('Column A | Column B');
    // The header row keeps its rule.
    expect(text.split('\n')[1]).toBe('-'.repeat('Column A | Column B'.length));
    expect(text.split('\n')[2]).toMatch(/^long text .* \| more words .*words$/);
  });

  it('flattens complex tables (spans, lists, code) into rows', () => {
    expect(txt(COMPLEX_TABLE)).toBe('Plan\n------+--------------------\nSteps | - first - second\nCode  | SELECT 1; SELECT 2;\n');
  });

  it('nests lists with two spaces', () => {
    expect(txt(NESTED_LISTS)).toBe('1. First\n  - Nested a\n  - Nested b\n    1. Deep\n2. Second\n\n4. Four\n5. Five\n');
  });

  it('keeps special characters literally', () => {
    const text = txt(SPECIAL_CHARS);
    expect(text).toContain('Use List<String> not List<String> and 2 * 3 = 6, snake_case_name, _emph_, [brackets], a \\ backslash &amp; and ~~strike~~.');
    expect(text).toContain('1. not a list\n\n# not a heading\n\n- not a bullet\n\n~~gone~~ 2');
  });

  it('marks strikethrough (also line-through spans)', () => {
    expect(txt('<p>a <s>old</s> <del>gone</del> <span style="text-decoration: line-through">x y</span> b</p>')).toBe('a ~~old~~ ~~gone~~ ~~x y~~ b\n');
  });

  it('puts the marker of an item that starts with code on its own line', () => {
    expect(txt('<ol><li><pre>shasum -c *.sha512</pre></li><li>Next</li></ol>')).toBe('1.\n      shasum -c *.sha512\n2. Next\n');
  });

  it('keeps runs of blank lines inside code blocks', () => {
    expect(txt('<pre>a\n\n\n\nb</pre><p>x</p>')).toBe('    a\n\n\n\n    b\n\nx\n');
  });

  it('describes images instead of linking them', () => {
    expect(txt(IMAGES_DEDUPE)).toContain('[Image: first]\n\n[Image: again]\n\n[Image: diagram v2.png]\n\n[Image: Logo]');
    expect(txt(FULL_PAGE)).toContain('[Image: flow.png]');
  });

  it('keeps placeholders with their links', () => {
    const r = convert(textInput([{ ref: ref('200', 'Page', 0), body: body('200', 'Page', IFRAME) }]));
    expect(r.placeholders).toBe(1);
    expect(r.files[0]!.text).toContain(
      "[Embedded content: Demo video] This content can't be included in this export. https://www.youtube.com/embed/abc123 (View it in Confluence: https://acme.atlassian.net/wiki/spaces/ENG/pages/200)",
    );
    expect(txt(INLINE_PLACEHOLDER)).toBe('Watch [Embedded media (vimeo.com): https://vimeo.com/123] now.\n');
  });

  it('maps emoticons and drops anchor markup', () => {
    expect(txt(EMOTICONS)).toBe('Good ✅ bad ❌ idea 💡 party :partyparrot:\n');
    expect(txt(ANCHORS)).toBe('Anchored paragraph.\n\njump and missing.\n');
  });
});
