import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { PDFArray, PDFDict, PDFDocument, PDFHexString, PDFName, PDFNumber, PDFRef, PDFString } from 'pdf-lib';
import { describe, expect, it } from 'vitest';
import {
  buildOutline,
  concatPdfs,
  finalizePdf,
  findDestinationPages,
  findSectionStartPages,
  readOutline,
  type OutlineItem,
} from '../../lib/pdf/merge';
import type { PageRef } from '../../lib/types';

// Real Chrome output, regenerated by scripts/experiments/make-pdf-fixtures.mjs.
// chrome-sections: [0] cover+TOC, [1] Alpha (p-101), [2..3] Beta (p-102), [4] Zażółć… (p-103)
// chrome-batch2:   [0] Delta (p-104)
// chrome-nodests:  [0] First, [1] Second, [2] "Third  title" — no named destinations
// chrome-live:     2 sheets, link "#later" → sheet 1, and its own colliding "p-101" dest
const fx = (name: string) => new Uint8Array(readFileSync(resolve(__dirname, 'fixtures', name)));
const SECTIONS = fx('chrome-sections.pdf');
const BATCH2 = fx('chrome-batch2.pdf');
const NODESTS = fx('chrome-nodests.pdf');
const LIVE = fx('chrome-live.pdf');
const GAMMA_TITLE = 'Zażółć gęślą jaźń — “quotes”';

const META = { title: 'Export', creator: 'Fast PDF Export for Confluence v1.0.0' };

/** Link annotations of a page: named dest name, or explicit dest page index, or URI. */
async function linksOf(bytes: Uint8Array) {
  const doc = await PDFDocument.load(bytes);
  const byRef = new Map(doc.getPages().map((p, i) => [p.ref.toString(), i]));
  return doc.getPages().map((page) => {
    const annots = page.node.lookup(PDFName.of('Annots'));
    if (!(annots instanceof PDFArray)) return [];
    const out: (string | number)[] = [];
    for (let i = 0; i < annots.size(); i++) {
      const a = annots.lookup(i, PDFDict);
      const dest = a.get(PDFName.of('Dest'));
      if (dest instanceof PDFName) out.push(`name:${dest.decodeText()}`);
      else if (dest instanceof PDFArray) out.push(byRef.get((dest.get(0) as PDFRef).toString()) ?? -1);
      else {
        const act = a.lookup(PDFName.of('A'));
        if (act instanceof PDFDict) out.push(`uri:${(act.lookup(PDFName.of('URI')) as PDFString).decodeText()}`);
      }
    }
    return out;
  });
}

const titles = (items: OutlineItem[]): unknown[] =>
  items.map((i) => (i.children.length ? [i.title, i.pageIndex, titles(i.children)] : [i.title, i.pageIndex]));

describe('findDestinationPages (Chrome catalog /Dests)', () => {
  it('maps p-{id} and heading destinations to sheet indexes', async () => {
    const m = await findDestinationPages(SECTIONS, ['p-101', 'p-102', 'p-103', 'p101-Intro', 'p102-Intro', 'p-999']);
    expect(Object.fromEntries(m)).toEqual({ 'p-101': 1, 'p-102': 2, 'p-103': 4, 'p101-Intro': 1, 'p102-Intro': 2 });
  });

  it('finds destinations created only by hidden links (no TOC)', async () => {
    expect(Object.fromEntries(await findDestinationPages(BATCH2, ['p-104']))).toEqual({ 'p-104': 0 });
  });

  it('returns nothing when Chrome emitted no destinations', async () => {
    expect((await findDestinationPages(NODESTS, ['p-201'])).size).toBe(0);
  });

  it('reads a /Names → /Dests name tree with Kids and string/hex keys', async () => {
    const doc = await PDFDocument.create();
    const pages = [doc.addPage(), doc.addPage(), doc.addPage()];
    const ctx = doc.context;
    const dest = (i: number) => ctx.obj([pages[i].ref, PDFName.of('Fit')]);
    const leafA = ctx.register(
      ctx.obj({ Limits: [PDFString.of('a'), PDFString.of('b')], Names: [PDFString.of('a'), dest(0), PDFHexString.fromText('b'), dest(1)] }),
    );
    const leafB = ctx.register(
      ctx.obj({ Names: [PDFHexString.fromText('ż-1'), ctx.obj({ D: dest(2) }), PDFString.of('ref'), ctx.register(dest(1))] }),
    );
    const tree = ctx.obj({ Kids: [leafA, leafB] });
    doc.catalog.set(PDFName.of('Names'), ctx.obj({ Dests: tree }));
    const bytes = await doc.save();
    const m = await findDestinationPages(bytes, ['a', 'b', 'ż-1', 'ref', 'nope']);
    expect(Object.fromEntries(m)).toEqual({ a: 0, b: 1, 'ż-1': 2, ref: 1 });
  });
});

describe('readOutline / findSectionStartPages', () => {
  it('reads Chrome’s nested outline, decoding UTF-16 titles', async () => {
    expect(titles(await readOutline(SECTIONS))).toEqual([
      ['Alpha page', 1, [['Intro of 101', 1]]],
      ['Beta page', 2, [['Intro of 102', 2]]],
      [GAMMA_TITLE, 4, [['Intro of 103', 4]]],
    ]);
  });

  it('uses destinations when present', async () => {
    const m = await findSectionStartPages(SECTIONS, [
      { id: '101', title: 'whatever' },
      { id: '102', title: 'Beta page' },
      { id: '103', title: GAMMA_TITLE },
    ]);
    expect(Object.fromEntries(m)).toEqual({ '101': 1, '102': 2, '103': 4 });
  });

  it('falls back to first-level outline titles in order (whitespace-insensitive)', async () => {
    const m = await findSectionStartPages(NODESTS, [
      { id: '201', title: 'First' },
      { id: '202', title: 'Second' },
      { id: 'x', title: 'Missing page' },
      { id: '203', title: 'Third   title' },
    ]);
    expect(Object.fromEntries(m)).toEqual({ '201': 0, '202': 1, '203': 2 });
  });

  it('matches duplicate titles in order', async () => {
    const doc = await PDFDocument.create();
    doc.addPage();
    doc.addPage();
    const base = await finalizePdf(await doc.save(), {
      metadata: META,
      outline: [
        { title: 'Same', pageIndex: 0, children: [] },
        { title: 'Same', pageIndex: 1, children: [] },
      ],
    });
    const m = await findSectionStartPages(base.bytes, [
      { id: 'a', title: 'Same' },
      { id: 'b', title: 'Same' },
    ]);
    expect(Object.fromEntries(m)).toEqual({ a: 0, b: 1 });
  });
});

describe('buildOutline', () => {
  const ref = (id: string, depth: number): PageRef => ({ id, depth, title: `T${id}`, type: 'page', url: '', reason: 'descendant' });
  it('nests by depth and skips pages without a start sheet', () => {
    const pages = [ref('1', 0), ref('2', 1), ref('3', 2), ref('4', 1), ref('5', 0), ref('6', 1)];
    const start = new Map([
      ['1', 0],
      ['2', 1],
      ['3', 2],
      ['4', 3],
      ['6', 5],
    ]);
    expect(titles(buildOutline(pages, start))).toEqual([
      ['T1', 0, [['T2', 1, [['T3', 2]]], ['T4', 3]]],
      // T5 has no start sheet: its child takes its place at the top level.
      ['T6', 5],
    ]);
  });
});

describe('concatPdfs', () => {
  it('returns a single part unchanged', async () => {
    const r = await concatPdfs([SECTIONS]);
    expect(r.bytes).toBe(SECTIONS);
    expect(r.offsets).toEqual([0]);
  });

  it('merges pages, named destinations and outlines with offsets', async () => {
    const r = await concatPdfs([SECTIONS, BATCH2]);
    expect(r.offsets).toEqual([0, 5]);
    const doc = await PDFDocument.load(r.bytes);
    expect(doc.getPageCount()).toBe(6);
    const m = await findDestinationPages(r.bytes, ['p-101', 'p-103', 'p-104', 'p104-Intro']);
    expect(Object.fromEntries(m)).toEqual({ 'p-101': 1, 'p-103': 4, 'p-104': 5, 'p104-Intro': 5 });
    expect(titles(await readOutline(r.bytes)).map((t) => (t as unknown[]).slice(0, 2))).toEqual([
      ['Alpha page', 1],
      ['Beta page', 2],
      [GAMMA_TITLE, 4],
      ['Delta page', 5],
    ]);
    const links = await linksOf(r.bytes);
    expect(links[0]).toEqual(['name:p-101', 'name:p-102', 'name:p-103']);
    expect(links[5]).toEqual(['uri:https://example.com/wiki/pages/104', 'name:p104-Intro']);
  });

  it('rejects an empty list', async () => {
    await expect(concatPdfs([])).rejects.toThrow();
  });
});

describe('finalizePdf', () => {
  it('inserts live pages after a section header and keeps base links, dests and outline valid', async () => {
    // Insert the 2-sheet live print right after Beta's first sheet (index 2).
    const r = await finalizePdf(SECTIONS, { metadata: META, inserts: [{ afterPageIndex: 2, pdf: LIVE }] });
    expect(r.pageCount).toBe(7);
    // Base destinations moved with their pages; live doc's own "p-101" did not override ours.
    const m = await findDestinationPages(r.bytes, ['p-101', 'p-102', 'p-103', 'later']);
    expect(Object.fromEntries(m)).toEqual({ 'p-101': 1, 'p-102': 2, 'p-103': 6 });
    const links = await linksOf(r.bytes);
    expect(links[0]).toEqual(['name:p-101', 'name:p-102', 'name:p-103']);
    // Inserted sheet 3: its internal links were rewritten to explicit destinations.
    expect(links[3]).toEqual([4, 4]);
    // Existing outline still points at the right (shifted) sheets.
    expect(titles(await readOutline(r.bytes)).map((t) => (t as unknown[]).slice(0, 2))).toEqual([
      ['Alpha page', 1],
      ['Beta page', 2],
      [GAMMA_TITLE, 6],
    ]);
    const doc = await PDFDocument.load(r.bytes);
    expect(doc.catalog.get(PDFName.of('PageMode'))).toEqual(PDFName.of('UseOutlines'));
    // No orphan page copies were created.
    const pageObjects = doc.context
      .enumerateIndirectObjects()
      .filter(([, o]) => o instanceof PDFDict && o.get(PDFName.of('Type')) === PDFName.of('Page'));
    expect(pageObjects.length).toBe(7);
  });

  it('applies several inserts from last to first, preserving order for equal positions', async () => {
    const one = await PDFDocument.create();
    one.addPage([100, 100]);
    const a = await one.save();
    const two = await PDFDocument.create();
    two.addPage([200, 200]);
    const b = await two.save();
    const r = await finalizePdf(SECTIONS, {
      metadata: META,
      inserts: [
        { afterPageIndex: -1, pdf: a },
        { afterPageIndex: 4, pdf: a },
        { afterPageIndex: 1, pdf: a },
        { afterPageIndex: 1, pdf: b },
      ],
    });
    const doc = await PDFDocument.load(r.bytes);
    const widths = doc.getPages().map((p) => Math.round(p.getWidth()));
    expect(widths).toEqual([100, 595, 595, 100, 200, 595, 595, 595, 100]);
    expect(Object.fromEntries(await findDestinationPages(r.bytes, ['p-101', 'p-103']))).toEqual({ 'p-101': 2, 'p-103': 7 });
  });

  it('replaces the outline, sets metadata and PageMode', async () => {
    const outline: OutlineItem[] = [
      { title: 'Root ✓', pageIndex: 1, children: [{ title: 'Child', pageIndex: 2, children: [{ title: 'Grandchild', pageIndex: 3, children: [] }] }] },
      { title: 'Second', pageIndex: 4, children: [] },
      { title: 'Out of range', pageIndex: 99, children: [] },
    ];
    const r = await finalizePdf(SECTIONS, {
      metadata: { ...META, author: 'Jane Doe', subject: 'Confluence export: ENG – 3 pages', keywords: ['ENG', 'Confluence'], producer: 'pdf' },
      outline,
    });
    expect(titles(await readOutline(r.bytes))).toEqual([
      ['Root ✓', 1, [['Child', 2, [['Grandchild', 3]]]]],
      ['Second', 4],
    ]);
    const doc = await PDFDocument.load(r.bytes, { updateMetadata: false });
    expect(doc.getTitle()).toBe('Export');
    expect(doc.getAuthor()).toBe('Jane Doe');
    expect(doc.getSubject()).toBe('Confluence export: ENG – 3 pages');
    expect(doc.getKeywords()).toBe('ENG Confluence');
    expect(doc.getCreator()).toBe(META.creator);
    expect(doc.getProducer()).toBe('pdf');
    expect(doc.getCreationDate()).toBeInstanceOf(Date);
    const vp = doc.catalog.lookup(PDFName.of('ViewerPreferences'), PDFDict);
    expect(String(vp.get(PDFName.of('DisplayDocTitle')))).toBe('true');
    // Outline counts: root shows 2 top items + Root's direct child; Child is closed (-1).
    const root = doc.catalog.lookup(PDFName.of('Outlines'), PDFDict);
    expect((root.get(PDFName.of('Count')) as PDFNumber).asNumber()).toBe(3);
    const first = root.lookup(PDFName.of('First'), PDFDict);
    expect((first.get(PDFName.of('Count')) as PDFNumber).asNumber()).toBe(1);
    const child = first.lookup(PDFName.of('First'), PDFDict);
    expect((child.get(PDFName.of('Count')) as PDFNumber).asNumber()).toBe(-1);
    expect(child.get(PDFName.of('Parent'))).toEqual(root.get(PDFName.of('First')));
  });

  it('an empty outline removes bookmarks and PageMode', async () => {
    const r = await finalizePdf(SECTIONS, { metadata: META, outline: [] });
    const doc = await PDFDocument.load(r.bytes);
    expect(doc.catalog.get(PDFName.of('Outlines'))).toBeUndefined();
    expect(doc.catalog.get(PDFName.of('PageMode'))).toBeUndefined();
  });

  it('can stamp page numbers', async () => {
    const r = await finalizePdf(NODESTS, { metadata: META, stampPageNumbers: { bottomPt: 20 } });
    expect(r.pageCount).toBe(3);
    const doc = await PDFDocument.load(r.bytes);
    const fonts = doc.getPages()[2].node.Resources()?.lookup(PDFName.of('Font'), PDFDict);
    expect(fonts?.keys().length).toBeGreaterThan(0);
  });
});
